### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [arbv/daemonize#1]
Interesting repo!  Is it still being maintained?

**Comment by arbv** [comment]
Well, it is. Honestly, I do not think it needs much update - probably some bugfixes if there are any bugs. The library itself, I believe, more or less complete (interface wise). It is a template code to simplify procedure of writing Unix daemons, so it is not rocket science :)

**Comment by Bohdan-Khomtchouk** [comment]
Thanks!  Do you have an email address I can reach you at?

**Comment by arbv** [comment]
Yes, I do. You can reach me via artem.boldarev at gmail.com.
